# Generated by Django 5.1.6 on 2025-03-25 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('place_name', models.CharField(max_length=255)),
                ('place_location', models.CharField(blank=True, max_length=255)),
                ('recommendation_reason', models.TextField(blank=True)),
                ('place_url', models.TextField(blank=True)),
                ('place_type', models.CharField(default='general', max_length=50)),
                ('event_date', models.CharField(blank=True, max_length=255)),
                ('additional_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
