services:
  backend:  
    build: .
    image: chatting_web:latest
    command: sh -c "python -c 'from chatbot.graph_chatbot import initialize_graph; initialize_graph()' && python manage.py migrate && daphne vacation.asgi:application --port 8000 --bind 0.0.0.0 -v2"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SETTINGS_MODULE=vacation.settings
      - TZ=Asia/Seoul

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=Asia/Seoul
    ports:
      - "5432:5432"

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - backend  

volumes:
  postgres_data:
  static_volume:
  media_volume: