# Generated by Django 5.1.6 on 2025-03-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatsession_recommended_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
