# Generated by Django 5.1.6 on 2025-03-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatsession_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_user',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
