# Generated by Django 5.1.6 on 2025-03-26 03:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatsession_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='session_id',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='url_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='recommended_places',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='새 채팅', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
